### PR TITLE
Document keyboard shortchuts

### PR DESCRIPTION
**Pull request by sebix**
as defined in `src/gui/src/store/settings.js`

### CODE REVIEW

**Comment by sebix** [comment]
If #46 is also merged either this  or the other PR needs a minor update

**Review by milankowww — CHANGES_REQUESTED** [review]
please only submit the Usage/keyboard.md. The other change to the global README makes "About" and "Learn more" subsections of "Architecture" which is not correct.

**Comment by sebix** [comment]
> The other change to the global README makes "About" and "Learn more" subsections of "Architecture" which is not correct.

No, the Architecture section is second-level as well, the same as About and Learn more with my proposed change. The first/top level is "Taranis NG" at the first line.

**Comment by dodancs** [comment]
> > The other change to the global README makes "About" and "Learn more" subsections of "Architecture" which is not correct.
> 
> No, the Architecture section is second-level as well, the same as About and Learn more with my proposed change. The first/top level is "Taranis NG" at the first line.

Okay, I'm with you @sebix on this one. The title Taranis NG has `#`, other chapters (Directory structure, Architecture, Getting started with Docker installation, About..., Learn more...) should have `##`.

**Review by dodancs — APPROVED** [review]

**Pull request merged**
