### PR TITLE
GUI (Assess): Show number of selected news items

### PR DESCRIPTION
**Pull request by sebix**
Right to the "News items count" display the "Selected news items count"
image

### CODE REVIEW

**Comment by sebix** [comment]
rebased on main and verified functionality OK

**Comment by milankowww** [comment]
This could look a bit prettier if implemented by vuetify badges: https://vuetifyjs.com/en/components/badges/#tabs

**Comment by sebix** [comment]
Like this? :flushed: 
image

**Review by milankowww — APPROVED** [review]
thank you for the PR

**Pull request merged**
