### PR TITLE
Add message presenter, updated .pre-commit-config.yaml - EMAIL UPDATE 1/2 

### PR DESCRIPTION
**Pull request by multiflexi**
As name suggests, message presenter outputs title and message body from templates. It outputs message_title and message_body. Email publisher in the second pull request either uses this or works similarly to the current state.

This commit also updates pre-commit configuration:
newer black version
added flake8
newer pre-commit-hooks version
added verification of yaml syntax and check if end of file ends with only newline

Feel free to suggest improvements.

### CODE REVIEW

**Comment by multiflexi** [comment]
I added max TLP and link prefix so it can be used in templates when multiple report items are selected.

**Comment by multiflexi** [comment]
Just included recommendations field for link prefix addition.

**Comment by multiflexi** [comment]
Fixed issues that caused MISP generation failure.

**Comment by multiflexi** [comment]
Simplified templates.

**Comment by multiflexi** [comment]
I think it is finished. Please review.

**Comment by multiflexi** [comment]
Added user data without password to product for presenters.

**Review by milankowww — APPROVED** [review]
thank you for the very fine contribution and sorry for the delay. Could you please in the future split updates to many smaller patches?

**Pull request merged**
